policies:
  - name: ensure-s3-bucket-policy-denies-http-requests
    resource: aws.s3
    filters:
      - type: missing-statement
        statement_ids:
          - DenyHTTPRequests
    actions:
      - type: set-bucket-policy
        add-statements:
          - Sid: DenyHTTPRequests
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - "arn:aws:s3:::{{ resource['Name'] }}"
              - "arn:aws:s3:::{{ resource['Name'] }}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"




