policies:
  - name: ensure-s3-bucket-policy-denies-http-requests
    resource: aws.s3
    filters:
      - type: missing-policy-statement
        statement:
          Effect: Deny
          Principal: "*"
          Action: "s3:*"
          Condition:
            Bool:
              aws:SecureTransport: "false"
    actions:
      - type: set-bucket-policy
        add-statements:
          - Sid: DenyHTTPRequests
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - "arn:aws:s3:::{{ resource['Name'] }}"
              - "arn:aws:s3:::{{ resource['Name'] }}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"



