policies:
  - name: AWS-CIS-2-1-1-ensure-s3-bucket-policy-denies-http-requests
    resource: aws.s3
    filters:
      - type: missing-policy-statement
        statement_ids:
          - DenyHTTPRequests
    actions:
      - type: set-statements
        statements:
          - Sid: DenyHTTPRequests
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - "arn:aws:s3:::{{ Name }}"
              - "arn:aws:s3:::{{ Name }}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"



















