policies:
  - name: aws-cis-1-8-ensure-iam-password-policy-min-length-14
    resource: account
    filters:
      - type: password-policy
        key: MinimumPasswordLength
        value: 14
        op: lt
    actions:
      - type: set-password-policy
        policy:
          MinimumPasswordLength: 14
