policies:
  - name: aws-cis-1-8-ensure-iam-password-policy-min-length-14
    resource: aws.account
    filters:
      - type: iam-password-policy
        MinimumPasswordLength: 14
    actions:
      - type: set-password-policy
        policy:
          MinimumPasswordLength: 14
